language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"

jobs:
  include:
    - stage: test
      script:
        - make
    - stage: test
      script:
        - (cd etc/browser-demo && make)
    - stage: test
      script: npm run lint
